name: 'devcontainer CI' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from github
        uses: actions/checkout@v3
      - name: "image name from repo name"
        id: docker_image_name
        run: echo "docker_image=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' |sed 's/[^0-9,a-z,A-Z,=,_,\/]/-/g' >>${GITHUB_OUTPUT}
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: devcontainer/${{ steps.docker_image_name.outputs.docker_image }}
          configFile: ./.devcontainer/devcontainer.json
          push: never
          runCmd: "bash -c 'source /opt/ros/humble/setup.bash && colcon build && source install/setup.bash && ros2 run param_inspector param_report'"